### ISSUE TITLE
怎麼缺少vctk_base.json ?

### ISSUE THREAD

**Issue by seq2193** [IceKyrin/sovits_infer_rcell#1]
剛才使用發現缺少 \configs\vctk_base.json  
麻煩處理一下,感謝!

**Comment by IceKyrin** [comment]
改成maolei.json了，忘了colab，colab已经改了

**Comment by seq2193** [comment]
![擷取](https://user-images.githubusercontent.com/109962092/191242178-2d8ce8eb-1866-4283-84a1-6a16d8128c7e.PNG)
![擷取2](https://user-images.githubusercontent.com/109962092/191242185-3a9e88fc-88e0-4bb6-8fe9-4a192fa497c3.PNG)
還是沒有改  麻煩修改一下,
建議加上  VOCAL 與伴奏的 gdown 上傳連接  我覺得會比較方便,謝謝!

**Comment by IceKyrin** [comment]
重新上传了一份vctk，也加了bgm的gdown，你刷新试试

**Comment by seq2193** [comment]
看到了 謝謝!
